<a href="https://colab.research.google.com/github/yandri918/belajar_machine_learning_buku_ONNO-W-Purba/blob/belajar_google_colab/24maret.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("penjualan_detail.csv")

In [ ]:
df.head()

,produk,jumlah,harga,omzet
0,Beras 5kg,12,74000,888000
1,Gula 1kg,20,17000,340000
2,Minyak 1L,15,21000,315000
3,Telur 1kg,18,28000,504000
4,Mi Instan,40,3500,140000


In [ ]:
def hitung_omzet_produk(jumlah, harga):
  return jumlah * harga

In [ ]:
def hitung_total_omzet(data):
  total = 0
  for item in data:
    total += item["omzet"]
  return total

In [ ]:
def hitung_rata_rata_omzet(data):
  if len(data) == 0:
    return 0
  return hitung_total_omzet(data) / len(data)

In [ ]:
def cari_produk_terlaris(data):
  if not data:
    return None
  produk_terlaris = data[0]
  for item in data:
    if item["jumlah"] > produk_terlaris["jumlah"]:
      produk_terlaris = item
  return produk_terlaris

In [ ]:
def cari_produk_omzet_tertinggi(data):
  if not data:
    return None
  produk_tertinggi = data[0]
  for item in data:
    if item["omzet"] > produk_tertinggi["omzet"]:
      produk_tertinggi = item
  return produk_tertinggi

In [ ]:
def cari_produk_omzet_terendah(data):
  if not data:
    return None
  produk_terendah = data[0]
  for item in data:
    if item["omzet"] < produk_terendah["omzet"]:
      produk_terendah = item
  return produk_terendah

In [ ]:
data_penjualan = []

In [ ]:
reader = pd.read_csv("penjualan_detail.csv")

In [ ]:
for index, row in reader.iterrows():
  produk = row["produk"]
  jumlah = int(row["jumlah"])
  harga = int(row["harga"])
  omzet = hitung_omzet_produk(jumlah, harga)
  data_penjualan.append({"produk": produk, "jumlah": jumlah, "harga": harga, "omzet": omzet})

In [ ]:
 data_penjualan.append({
     "produk": produk,
     "jumlah": jumlah,
    "harga": harga,
     "omzet": omzet         })

In [ ]:
total_omzet = hitung_total_omzet(data_penjualan)
rata_rata_omzet = hitung_rata_rata_omzet(data_penjualan)
produk_terlaris = cari_produk_terlaris(data_penjualan)
produk_tertinggi = cari_produk_omzet_tertinggi(data_penjualan)
produk_terendah = cari_produk_omzet_terendah(data_penjualan)

In [ ]:
if produk_terlaris is not None:
    print("Produk terlaris:", produk_terlaris["produk"])
else:
    print("Produk terlaris: Not found or function error.")

if produk_tertinggi is not None:
    print("Omzet tertinggi:", produk_tertinggi["produk"], produk_tertinggi["omzet"])
else:
    print("Omzet tertinggi: Not found or function error.")

if produk_terendah is not None:
    print("Omzet terendah:", produk_terendah["produk"], produk_terendah["omzet"])
else:
    print("Omzet terendah: Not found or function error.")

Produk terlaris: Mi Instan
Omzet tertinggi: Beras 5kg 888000
Omzet terendah: Mi Instan 140000


In [ ]:
print("Total omzet:", total_omzet)
print("Rata-rata omzet:", rata_rata_omzet)

Total omzet: 4654000
Rata-rata omzet: 387833.3333333333


In [ ]:
import numpy as np

In [ ]:
matriks_nilai = np.array([ [80, 85, 90], [75, 88, 92] ])

In [ ]:
print("Array 2D:")
print(matriks_nilai)
print("Shape:", matriks_nilai.shape)

Array 2D:
[[80 85 90]
 [75 88 92]]
Shape: (2, 3)


In [ ]:
arr_zeros = np.zeros((2, 3))
arr_ones = np.ones((3, 2))
arr_range = np.arange(0, 10, 2)

In [ ]:
print("Array nol:")
print(arr_zeros)

Array nol:
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print("\nArray satu:")
print(arr_ones)


Array satu:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
print("\nArray rentang:")
print(arr_range)


Array rentang:
[0 2 4 6 8]


In [ ]:
data = np.array([10, 20, 30, 40])

In [ ]:
print("Tambah 5:", data + 5)
print("Kali 2:", data * 2)
print("Bagi 10:", data / 10)

Tambah 5: [15 25 35 45]
Kali 2: [20 40 60 80]
Bagi 10: [1. 2. 3. 4.]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

In [ ]:
print("Elemen pertama:", arr[0])
print("Elemen ketiga:", arr[2])
print("Elemen terakhir:", arr[-1])

Elemen pertama: 10
Elemen ketiga: 30
Elemen terakhir: 50


In [ ]:
print("Dua elemen pertama:", arr[:2])
print("Elemen indeks 1 sampai 3:", arr[1:4])
print("Mulai indeks 2 sampai akhir:", arr[2:])

Dua elemen pertama: [10 20]
Elemen indeks 1 sampai 3: [20 30 40]
Mulai indeks 2 sampai akhir: [30 40 50]


In [ ]:
arr2d = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])

In [ ]:
print("Dua baris pertama, dua kolom terakhir:",(arr2d[0:2, 1:3]))

Dua baris pertama, dua kolom terakhir: [[2 3]
 [5 6]]


In [ ]:
arr = np.arange(1, 10)
print("Array asli:")
print(arr)

Array asli:
[1 2 3 4 5 6 7 8 9]


In [ ]:
reshaped = arr.reshape(3, 3)
print("\nArray setelah reshape 3x3:")
print(reshaped)


Array setelah reshape 3x3:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
umur = np.array([18, 19, 20, 21, 22])
X = umur.reshape(-1, 1)
print("Array asli:", umur)
print("Shape asli:", umur.shape)

Array asli: [18 19 20 21 22]
Shape asli: (5,)


In [ ]:
print("\nSetelah reshape:")
print(X)
print("Shape baru:", X.shape)


Setelah reshape:
[[18]
 [19]
 [20]
 [21]
 [22]]
Shape baru: (5, 1)


In [ ]:
vektor_a = np.array([1, 2, 3])
vektor_b = np.array([4, 5, 6])

In [ ]:
print("Penjumlahan vektor:", vektor_a + vektor_b)
print("Pengurangan vektor:", vektor_a - vektor_b)

Penjumlahan vektor: [5 7 9]
Pengurangan vektor: [-3 -3 -3]


In [ ]:
print("Perkalian elemen-per-elemen:", vektor_a * vektor_b)

Perkalian elemen-per-elemen: [ 4 10 18]


In [ ]:
dot_hasil = np.dot(vektor_a, vektor_b)

In [ ]:
print(dot_hasil)

32


In [ ]:
A = np.array([ [1, 2], [3, 4] ])
B = np.array([ [5, 6], [7, 8] ])

In [ ]:
print("A + B:")
print(A + B)

A + B:
[[ 6  8]
 [10 12]]


In [ ]:
print("\nA - B:",A-B)



A - B: [[-4 -4]
 [-4 -4]]


In [ ]:
print("Perkalian elemen matriks:")
print(A * B)

Perkalian elemen matriks:
[[ 5 12]
 [21 32]]


In [ ]:
print("Perkalian matriks:")
print(A @ B)

Perkalian matriks:
[[19 22]
 [43 50]]


In [ ]:
nilai = np.array([80, 75, 90])
bobot = np.array([0.3, 0.3, 0.4])

In [ ]:
nilai_akhir = np.dot(nilai, bobot)
print("Nilai akhir:", nilai_akhir)

Nilai akhir: 82.5


In [ ]:
data = np.array([100, 75, 80, 85, 90])

In [ ]:
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Variance:", np.var(data))
print("Standard deviation:", np.std(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Jumlah total:", np.sum(data))

Mean: 86.0
Median: 85.0
Variance: 74.0
Standard deviation: 8.602325267042627
Minimum: 75
Maximum: 100
Jumlah total: 430


In [ ]:
nilai_kelas = np.array([ [80, 85, 90], [95, 88, 92] ])

In [ ]:
print("Mean seluruh array:", np.mean(nilai_kelas))
print("Mean per kolom:", np.mean(nilai_kelas, axis=0))
print("Mean per baris:", np.mean(nilai_kelas, axis=1))

Mean seluruh array: 88.33333333333333
Mean per kolom: [87.5 86.5 91. ]
Mean per baris: [85.         91.66666667]


In [ ]:
penjualan = np.array([5700, 6200, 6500, 5980, 5800, 6480])

In [ ]:
mean_penjualan = np.mean(penjualan)
std_penjualan = np.std(penjualan)
minimum = np.min(penjualan)
maksimum = np.max(penjualan)

In [ ]:
print("Rata-rata penjualan:", mean_penjualan)
print("Standar deviasi:", std_penjualan)
print("Penjualan minimum:", minimum)
print("Penjualan maksimum:", maksimum)

Rata-rata penjualan: 6110.0
Standar deviasi: 310.42980956516834
Penjualan minimum: 5700
Penjualan maksimum: 6500


In [ ]:
data = np.array([49, 51, 46, 54, 50, 50])

In [ ]:
print("Std populasi:", np.std(data))
print("Std sampel :", np.std(data, ddof=1))

Std populasi: 2.3804761428476167
Std sampel : 2.6076809620810595


In [ ]:
nilai = np.array([82, 76, 91, 88, 79, 95, 84])

In [ ]:
print("Data nilai:", nilai)
print("Jumlah data:", len(nilai))
print("Rata-rata:", np.mean(nilai))
print("Median:", np.median(nilai))
print("Nilai minimum:", np.min(nilai))
print("Nilai maksimum:", np.max(nilai))
print("Variance:", np.var(nilai))
print("Std dev:", np.std(nilai))

Data nilai: [82 76 91 88 79 95 84]
Jumlah data: 7
Rata-rata: 85.0
Median: 84.0
Nilai minimum: 76
Nilai maksimum: 95
Variance: 38.857142857142854
Std dev: 6.233549779791836


In [ ]:
import numpy as np
print("=" * 60)
print("LATIHAN TERPADU NUMPY")
print("=" * 60)

LATIHAN TERPADU NUMPY


In [ ]:
nilai = np.array([80, 85, 90, 75, 88, 92, 78])
print("\n1. Array nilai:")
print(nilai)
print("Shape:", nilai.shape)


1. Array nilai:
[80 85 90 75 88 92 78]
Shape: (7,)


In [ ]:
print("\n2. Indexing dan slicing:")
print("Elemen pertama :", nilai[0])
print("Elemen terakhir:", nilai[-1])
print("Tiga elemen awal:", nilai[:3])
print("Elemen indeks 2 sampai 5:", nilai[2:6])


2. Indexing dan slicing:
Elemen pertama : 80
Elemen terakhir: 78
Tiga elemen awal: [80 85 90]
Elemen indeks 2 sampai 5: [90 75 88 92]


In [ ]:
print("\n3. Operasi numerik:")
print("Nilai + 5 :", nilai + 5)
print("Nilai * 2 :", nilai * 2)


3. Operasi numerik:
Nilai + 5 : [85 90 95 80 93 97 83]
Nilai * 2 : [160 170 180 150 176 184 156]


In [ ]:
print("\n4. Reshape ke 2D:")
nilai_2d = nilai[:6].reshape(2, 3)
print(nilai_2d)
print("Shape baru:", nilai_2d.shape)
print("\n5. Operasi vektor:")


4. Reshape ke 2D:
[[80 85 90]
 [75 88 92]]
Shape baru: (2, 3)

5. Operasi vektor:


In [ ]:
bobot = np.array([0.3, 0.3, 0.4])
nilai_siswa = np.array([80, 75, 90])
nilai_akhir = np.dot(nilai_siswa, bobot)

In [ ]:
print("Nilai siswa:", nilai_siswa)
print("Bobot      :", bobot)
print("Nilai akhir:", nilai_akhir)

Nilai siswa: [80 75 90]
Bobot      : [0.3 0.3 0.4]
Nilai akhir: 82.5


In [ ]:
print("\n6. Operasi matriks:")
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])


6. Operasi matriks:


In [ ]:
print("A + B:")
print(A + B)
print("A * B (elemen-per-elemen):")
print(A * B)
print("A @ B (perkalian matriks):")
print(A @ B)

A + B:
[[ 6  8]
 [10 12]]
A * B (elemen-per-elemen):
[[ 5 12]
 [21 32]]
A @ B (perkalian matriks):
[[19 22]
 [43 50]]


In [ ]:
print("Mean   :", np.mean(nilai))
print("Median :", np.median(nilai))
print("Min    :", np.min(nilai))
print("Max    :", np.max(nilai))
print("Var    :", np.var(nilai))
print("Std    :", np.std(nilai))

Mean   : 84.0
Median : 85.0
Min    : 75
Max    : 92
Var    : 35.714285714285715
Std    : 5.976143046671968


In [ ]:
kelas = np.array([ [80, 85, 90], [75, 88, 92], [78, 81, 84] ])

In [ ]:
print("Array kelas:")
print(kelas)
print("Mean per kolom:", np.mean(kelas, axis=0))
print("Mean per baris:", np.mean(kelas, axis=1))

Array kelas:
[[80 85 90]
 [75 88 92]
 [78 81 84]]
Mean per kolom: [77.66666667 84.66666667 88.66666667]
Mean per baris: [85. 85. 81.]


In [ ]:
print("\nSelesai. Anda sudah memakai NumPy untuk komputasi numerik dasar.")
print("=" * 60)


Selesai. Anda sudah memakai NumPy untuk komputasi numerik dasar.
